MATCHLOGINDEXES = [
  [
    "MatchLeagueNumber",
    "MatchSeason",
    "MatchWeek",
    "MatchResult",
    "ClubMatchLogs",
  ],
  ["MatchLeagueNumber", "MatchSeason", "MatchWeek", "MatchResult"],
  ["MatchLeagueNumber", "MatchSeason", "MatchWeek", "ClubMatchLogs"],
  ["MatchLeagueNumber", "MatchSeason", "MatchWeek"],
  ["MatchLeagueNumber", "MatchSeason", "MatchResult", "ClubMatchLogs"],
  ["MatchLeagueNumber", "MatchSeason", "MatchResult"],
  ["MatchLeagueNumber", "MatchSeason", "ClubMatchLogs"],
  ["MatchLeagueNumber", "MatchSeason"],
  ["MatchLeagueNumber", "MatchWeek", "MatchResult", "ClubMatchLogs"],
  ["MatchLeagueNumber", "MatchWeek", "MatchResult"],
  ["MatchLeagueNumber", "MatchWeek", "ClubMatchLogs"],
  ["MatchLeagueNumber", "MatchWeek"],
  ["MatchLeagueNumber", "MatchResult", "ClubMatchLogs"],
  ["MatchLeagueNumber", "MatchResult"],
  ["MatchLeagueNumber", "ClubMatchLogs"],
  ["MatchLeagueNumber"],
  ["MatchSeason", "MatchWeek", "MatchResult", "ClubMatchLogs"],
  ["MatchSeason", "MatchWeek", "MatchResult"],
  ["MatchSeason", "MatchWeek", "ClubMatchLogs"],
  ["MatchSeason", "MatchWeek"],
  ["MatchSeason", "MatchResult", "ClubMatchLogs"],
  ["MatchSeason", "MatchResult"],
  ["MatchSeason", "ClubMatchLogs"],
  ["MatchSeason"],
  ["MatchWeek", "MatchResult", "ClubMatchLogs"],
  ["MatchWeek", "MatchResult"],
  ["MatchWeek", "ClubMatchLogs"],
  ["MatchWeek"],
  ["MatchResult", "ClubMatchLogs"],
  ["MatchResult"],
  ["ClubMatchLogs"],
  [],
];
