import { BaseCountry } from "./CountryTypes";
export const premierLeagueClubs: Array<string> = [
  "Liverpool",
  "Man United",
  "Leeds United",
  "Arsenal",
  "Spurs",
  "Aston Villa",
  "Everton",
  "Nottm Forest",
  "Millwall",
  "Coventry",
  "West Ham",
  "Norwich",
  "Sheff Wed",
  "Derby",
  "Chelsea",
  "Newcastle",
];

export const championshipClubs: Array<string> = [
  "Watford",
  "Stoke City",
  "Brighton",
  "Barnsley",
  "Plymouth",
  "Hull City",
  "Notts Co",
  "Man City",
  "Shrewsbury",
  "Burnley",
  "Charlton",
  "Sunderland",
  "Bradford",
  "Bury",
  "Sheff United",
  "Huddersfield",
];

export const leagueOneClubs: Array<string> = [
  "Wolves",
  "Oxford",
  "Swindon",
  "Walsall",
  "Newport",
  "Wigan",
  "Wimbledon",
  "Mansfield",
  "Southend",
  "Grimsby",
  "Blackburn",
  "Reading",
  "Crewe",
  "Darlington",
  "Port Value",
  "Stockport",
];

export const leagueTwoClubs: Array<string> = [
  "Scunthorpe",
  "York",
  "Bournemouth",
  "Doncaster",
  "Lincoln",
  "Rochdale",
  "Hereford",
  "Hartlepool",
  "Halifax",
  "Tranmere",
  "Aldershot",
  "Bristol",
  "Wrexham",
  "Torquay",
  "Gillingham",
  "Exeter",
];

export const England: BaseCountry = [
  "England",
  ["English Premier League", "The Championship", "League One", "League Two"],
  [premierLeagueClubs, championshipClubs, leagueOneClubs, leagueTwoClubs],
];

export const BASEENGLANDCOMPOSITION = [
  ["England",	255],
  ["Brazil",	34],
  ["France",	27],
  ["Netherlands",	25],
  ["Portugal",	23],
  ["Republic of Ireland",	22],
  ["Spain",	19],
["Denmark",	19],
["Argentina",	15],
["Germany",	13],
["Scotland",	13],
["Belgium",	10],
["Sweden",	10],
["Italy",	10],
["Wales",	10],
["Nigeria",	9],
["Ghana",	8],
["Poland",	8],
["Côte d'Ivoire",	7],
["Colombia",	6],
["United States",	6],
["Senegal",	5],
["Norway",	5],
["Ukraine",	5],
["Japan",	5],
["Jamaica",	5],
["Mali",	5],
["Northern Ireland",	5],
["Uruguay",	4],
["Czech Republic",	4],
["Korea Republic",	4],
["Paraguay",	4],
["Türkiye",	4],
["Cameroon",	3],
["Egypt",	3],
["Serbia",	3],
["Ecuador",	3],
["Mexico",	3],
["Morocco",	3],
["Greece",	3],
["Burkina Faso",	3],
["Australia",	3],
["Hungary",	2],
["Croatia",	2],
["Switzerland",	2],
["Congo DR",	2],
["Zimbabwe",	2],
["Albania",	2],
["Algeria",	1],
["New Zealand",	1],
["Kosovo",	1],
["Gabon",	1],
["Gambia",	1],
["Romania",	1],
["Guinea-Bissau",	1],
["Slovakia",	1],
["Uzbekistan",	1],
["Chile",	1],
["Zambia",	1],
["Austria",	1],
["Iceland",	1],
["Iraq",	1],
["Montserrat",	1],
["Barbados",	1],
["Bosnia and Herzegovina",	1]
]

