import { COUNTRYNAMES, FIRSTNAMES, LASTNAMES } from "./Names";

export enum PLAYERIDINDICES {
  CountryNumber = "0",
  DomesticLeagueID = "1",
  DomesticLeagueLevel = "2",
  ClubID = "3",
  SquadNumber = "4",
  PositionGroup = "5",
  Position = "6",
  PlayerNumber = "7",
  Season = "8",
}

export const COUNTRYNAMESRANGE: [number, number] = [0, COUNTRYNAMES.length];
export const FIRSTNAMESRANGE: [number, number] = [0, FIRSTNAMES.length];
export const LASTNAMESRANGE: [number, number] = [0, LASTNAMES.length];

export enum PositionGroup {
  Forward = "0",
  Midfielder = "1",
  Defender = "2",
  Goalkeeper = "3",
}

export enum ALLPOSITIONS {
  LW = "0",
  RW = "1",
  ST = "2",
  CF = "3",

  RCB = "4",
  LCB = "5",
  LB = "6",
  RB = "7",

  CDM = "8",
  CM = "9",
  RM = "10",
  LM = "11",

  // Line keeper
  LK = "12",
  // Sweeper keeper
  SK = "13",
  // Ball-Playing Keeper
  BPK = "14",
}

// ranges are not inclusive
// LW, RW, ST, CF
export const FORWARDPOSITIONGROUPRANGES: [number, number] = [0, 4];
// LM. RM, CM, CDM
export const MIDFIELDERPOSITIONGROUPRANGES: [number, number] = [4, 8];
// LB, RB, LCB, RCB
export const DEFENDERPOSITIONGROUPRANGES: [number, number] = [8, 12];
// LK, SK, BPK
export const GOALKEEPERPOSITIONGROUPRANGES: [number, number] = [12, 15];

export const DEFAULTMINAGE: number = 18;
export const DEFAULTAGERANGE: [number, number] = [DEFAULTMINAGE, 38];
export const MAXCONTRACTYEARS: number = 5;
export const DEFAULTCONTRACTYEARSRANGE: [number, number] = [
  1,
  MAXCONTRACTYEARS + 1,
];
export const DEFAULTMANAGEREFFECT: [number, number] = [0, 10];
export const DEFAULTHEIGHTRANGE: [number, number] = [160, 200];
export const DEFAULTWEIGHRANGE: [number, number] = [60, 100];

export const POSITIONGROUPSCOUNT: number = 4;
export const POSITIONGROUPSRANGE: [number, number] = [0, POSITIONGROUPSCOUNT];

export const POSITIONPRIMARYSKILLSRANGE: [number, number] = [50, 99];
export const POSITIONSECONDARYSKILLSRANGE: [number, number] = [25, 75];
export const BASICSKILLSRANGE: [number, number] = [25, 99];
export const OTHERSKILLSRANGE: [number, number] = [25, 50];
export const SKILLCEILINGADJUSTMENTBYDIVISION: Array<number> = [
  1, 0.75, 0.5, 0.45, 0.4,
];

// Source: https://www.capology.com/uk/premier-league/payrolls/2024-2025/
export const PREMIERLEAGUEPAYROLLPERPOSITIONGROUP: Array<number> = [
  780_904_800, 428_838_800, 665_771_600, 158_085_200,
];
export const WAGERANGEFOROUTFIELDPLAYERS: [number, number] = [0, 7];
export const WAGERANGEFORGOALKEEPERS: [number, number] = [0, 4];

export enum PLAYERBIODATA {
  Age = "0",
  YearsLeftOnContract = "1",
  Wages = "2",
  Height = "3",
  Weight = "4",
  ManagerEffect = "5",
  //above data is not adjusted per division

  Tackling = "6",
  Passing = "7",
  Shooting = "8",
  Dribbling = "9",

  Marking = "10",
  Vision = "11",
  Strength = "12",

  AttackingWorkRate = "13",
  DefendingWorkRate = "14",
  PositionalAwareness = "15",
  SprintSpeed = "16",
  Agility = "17",

  GKPositioning = "18",
  GKDiving = "19",
  GKHandling = "20",
  GKReflexes = "21",
}

export enum DEFENDINGSKILLS {
  Tackling = "0",
  Marking = "8",
  PositionalAwareness = "13",
  SprintSpeed = "14",
  Agility = "15",
  DefendingWorkRate = "12",
}

export enum GOALKEEPINGSKILLS {
  GKPositioning = "16",
  GKDiving = "17",
  GKHandling = "18",
  GKReflexes = "19",
}

export enum ATTACKINGSKILLS {
  Passing = "5",
  Shooting = "6",
  Dribbling = "7",
  Vision = "9",
  AttackingWorkRate = "11",
  PositionalAwareness = "13",
  SprintSpeed = "14",
}

export const PLAYERBIODATARANGESBYPOSITION: Record<
  PositionGroup,
  Record<string, [number, number]>
> = {
  [PositionGroup.Forward]: {
    [PLAYERBIODATA.Age]: DEFAULTAGERANGE,
    [PLAYERBIODATA.YearsLeftOnContract]: DEFAULTCONTRACTYEARSRANGE,
    [PLAYERBIODATA.Wages]: WAGERANGEFOROUTFIELDPLAYERS,
    [PLAYERBIODATA.Height]: DEFAULTHEIGHTRANGE,
    [PLAYERBIODATA.Weight]: DEFAULTWEIGHRANGE,
    [PLAYERBIODATA.ManagerEffect]: DEFAULTMANAGEREFFECT,

    [PLAYERBIODATA.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Dribbling]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Strength]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
  },
  [PositionGroup.Midfielder]: {
    [PLAYERBIODATA.Age]: DEFAULTAGERANGE,
    [PLAYERBIODATA.YearsLeftOnContract]: DEFAULTCONTRACTYEARSRANGE,
    [PLAYERBIODATA.Wages]: WAGERANGEFOROUTFIELDPLAYERS,
    [PLAYERBIODATA.Height]: DEFAULTHEIGHTRANGE,
    [PLAYERBIODATA.Weight]: DEFAULTWEIGHRANGE,
    [PLAYERBIODATA.ManagerEffect]: DEFAULTMANAGEREFFECT,

    [PLAYERBIODATA.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Dribbling]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Strength]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
  },
  [PositionGroup.Defender]: {
    [PLAYERBIODATA.Age]: DEFAULTAGERANGE,
    [PLAYERBIODATA.YearsLeftOnContract]: DEFAULTCONTRACTYEARSRANGE,
    [PLAYERBIODATA.Wages]: WAGERANGEFOROUTFIELDPLAYERS,
    [PLAYERBIODATA.Height]: DEFAULTHEIGHTRANGE,
    [PLAYERBIODATA.Weight]: DEFAULTWEIGHRANGE,
    [PLAYERBIODATA.ManagerEffect]: DEFAULTMANAGEREFFECT,

    [PLAYERBIODATA.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Dribbling]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Strength]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
  },
  [PositionGroup.Goalkeeper]: {
    [PLAYERBIODATA.Age]: DEFAULTAGERANGE,
    [PLAYERBIODATA.YearsLeftOnContract]: DEFAULTCONTRACTYEARSRANGE,
    [PLAYERBIODATA.Wages]: WAGERANGEFORGOALKEEPERS,
    [PLAYERBIODATA.Height]: DEFAULTHEIGHTRANGE,
    [PLAYERBIODATA.Weight]: DEFAULTWEIGHRANGE,
    [PLAYERBIODATA.ManagerEffect]: DEFAULTMANAGEREFFECT,

    [PLAYERBIODATA.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Dribbling]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Strength]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERBIODATA.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERBIODATA.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
  },
};

export enum PLAYERSTATISTICSINDICES {
  Minutes = "0",
  Goals = "1",
  Assists = "2",
  Touches = "3",
  Tackles = "4",
  Passes = "5",
}
