import { COUNTRYNAMES, FIRSTNAMES, LASTNAMES } from "./Names";

export enum PositionGroup {
  Forward = "0",
  Midfielder = "1",
  Defender = "2",
  Goalkeeper = "3",
}

export enum PLAYERBIODATA {
  FirstName = "0",
  LastName = "1",
  NationalTeam = "2"    
}

export enum PLAYERIDINDICES {
  Season = "0",
  Country = "1",
  DomesticLeague = "2",
  DomesticLeagueLevel = "3",
  Club = "4",
  PositionGroup = "5",
  Position = "6",  
  PlayerNumber = "7",
  
  Age = "8",  
  ManagerEffect = "9",
  YearsLeftOnContract = "10",
  Wages = "11",    
  
  Tackling = "12",
  Passing = "13",
  Shooting = "14",
  Dribbling = "15",

  Marking = "16",
  Vision = "17",
  Strength = "18",

  AttackingWorkRate = "19",
  DefendingWorkRate = "20",
  PositionalAwareness = "21",
  SprintSpeed = "22",
  Agility = "23",

  GKPositioning = "24",
  GKDiving = "25",
  GKHandling = "26",
  GKReflexes = "27",

  Height = "28",
  Weight = "29",  
}

export enum ALLPOSITIONS {
  LW="0",
  RW="1",
  ST="2",
  CF="3",

  RCB="4",
  LCB="5",
  LB="6",
  RB="7",

  CDM="8",
  CM="9",
  RM="10",
  LM="11",
  
  // Line keeper
  LK="12",
  // Sweeper keeper
  SK="13",
  // Ball-Playing Keeper
  BPK="14"
}

export enum DEFENDINGSKILLS {
  Tackling = "0",
  Marking = "8",
  PositionalAwareness = "13",
  SprintSpeed = "14",
  Agility = "15",
  DefendingWorkRate = "12"
}

export enum GOALKEEPINGSKILLS {
  GKPositioning = "16",
  GKDiving = "17",
  GKHandling = "18",
  GKReflexes = "19",
}

export enum ATTACKINGSKILLS {
  Passing = "5",
  Shooting = "6",
  Dribbling = "7",
  Vision = "9",
  AttackingWorkRate = "11",
  PositionalAwareness = "13",
  SprintSpeed = "14"
}



export const DEFAULTMINAGE: number = 18;
export const DEFAULTAGERANGE: [number, number] = [DEFAULTMINAGE, 38];

export const MAXCONTRACTYEARS: number = 5

export const FORWARDWAGESRANGE: [number, number] = [2_000, 500_000];
export const DEFENDERWAGESRANGE: [number, number] = [2_000, 350_000];
export const MIDFIELDERWAGESRANGE: [number, number] = [2_000, 350_000];
export const GOALKEEPERWAGESRANGE: [number, number] = [2_000, 150_000];
export const WAGECEILINGADJUSTMENTBYDIVISION: Array<number> = [1, 0.75, 0.50, 0.45, 0.40]

export const TOTALPLAYERIDINDICIES: number = Object.keys(PLAYERIDINDICES).length

export const POSITIONGROUPSCOUNT: number = 4
export const POSITIONGROUPSRANGE: [number, number] = [0,3]

export const PLAYERIDINDICESRANGE: [number, number] = [0, TOTALPLAYERIDINDICIES-1]
export const PLAYERSKILLSONLYINDICESRANGE: [number, number] = [11,27]


export const FIRSTNAMESRANGE: [number, number] = [0, FIRSTNAMES.length]
export const LASTNAMESRANGE: [number, number] = [0, LASTNAMES.length]
export const COUNTRYNAMESRANGE: [number, number] = [0, COUNTRYNAMES.length]

export const HEIGHTRANGE: [number, number] = [160, 200];
export const WEIGHTRANGE: [number, number] = [60, 100];

export const POSITIONPRIMARYSKILLSRANGE: [number, number] = [50, 99];
export const POSITIONSECONDARYSKILLSRANGE: [number, number] = [25, 75];
export const BASICSKILLSRANGE: [number, number] = [25, 99];
export const OTHERSKILLSRANGE: [number, number] = [25, 50];
export const SKILLCEILINGADJUSTMENTBYDIVISION: Array<number> = [1, 0.75, 0.50, 0.45, 0.40]


// ranges are not inclusive
// LW, RW, ST, CF
export const FORWARDPOSITIONGROUPRANGES: [number, number] = [0,4]
// LM. RM, CM, CDM
export const MIDFIELDERPOSITIONGROUPRANGES: [number, number] = [4,8]
// LB, RB, LCB, RCB
export const DEFENDERPOSITIONGROUPRANGES: [number, number] = [8,12]
// LK, SK, BPK
export const GOALKEEPERPOSITIONGROUPRANGES: [number, number] = [12,15]


export const PLAYERBIODATARANGESBYPOSITION: Record<PositionGroup, Array<[number, number]>> = {  
  [PositionGroup.Forward]: [
    FIRSTNAMESRANGE,
    LASTNAMESRANGE,
    COUNTRYNAMESRANGE,
    FORWARDPOSITIONGROUPRANGES,
    HEIGHTRANGE,
    WEIGHTRANGE,
  ],
  [PositionGroup.Midfielder]: [
    FIRSTNAMESRANGE,
    LASTNAMESRANGE,
    COUNTRYNAMESRANGE,
    MIDFIELDERPOSITIONGROUPRANGES,
    HEIGHTRANGE,
    WEIGHTRANGE,
  ],
  [PositionGroup.Defender]: [
    FIRSTNAMESRANGE,
    LASTNAMESRANGE,
    COUNTRYNAMESRANGE,
    DEFENDERPOSITIONGROUPRANGES,
    HEIGHTRANGE,
    WEIGHTRANGE,
  ],
  [PositionGroup.Goalkeeper]: [
    FIRSTNAMESRANGE,
    LASTNAMESRANGE,
    COUNTRYNAMESRANGE,
    GOALKEEPERPOSITIONGROUPRANGES,
    HEIGHTRANGE,
    WEIGHTRANGE,
  ]    
}
 


export const PLAYERIDDATARANGESBYPOSITION: Record<PositionGroup,
  Record<string, [number, number]>>
  = {
    [PositionGroup.Forward]: {

      [PLAYERIDINDICES.PositionGroup]: FORWARDPOSITIONGROUPRANGES,
      [PLAYERIDINDICES.Wages]: FORWARDWAGESRANGE,

      [PLAYERIDINDICES.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Dribbling]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Strength]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERIDINDICES.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
    },
    [PositionGroup.Midfielder]: {

      [PLAYERIDINDICES.PositionGroup]: MIDFIELDERPOSITIONGROUPRANGES,
      [PLAYERIDINDICES.Wages]: MIDFIELDERWAGESRANGE,
      
    [PLAYERIDINDICES.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Dribbling]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Strength]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERIDINDICES.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
  },  
    [PositionGroup.Defender]: {
      
      [PLAYERIDINDICES.PositionGroup]: DEFENDERPOSITIONGROUPRANGES,
      [PLAYERIDINDICES.Wages]: DEFENDERWAGESRANGE,

    [PLAYERIDINDICES.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Dribbling]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Strength]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERIDINDICES.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
  },  
    [PositionGroup.Goalkeeper]: {

      [PLAYERIDINDICES.PositionGroup]: GOALKEEPERPOSITIONGROUPRANGES,
      [PLAYERIDINDICES.Wages]: GOALKEEPERWAGESRANGE,
      
    [PLAYERIDINDICES.Tackling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Passing]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Shooting]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Dribbling]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.Marking]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Vision]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Strength]: POSITIONSECONDARYSKILLSRANGE,
    
    [PLAYERIDINDICES.AttackingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.DefendingWorkRate]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.PositionalAwareness]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.SprintSpeed]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.Agility]: POSITIONSECONDARYSKILLSRANGE,

    [PLAYERIDINDICES.GKPositioning]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKDiving]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKHandling]: POSITIONSECONDARYSKILLSRANGE,
    [PLAYERIDINDICES.GKReflexes]: POSITIONSECONDARYSKILLSRANGE,
  }  
}    
